#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Minkiele\IpFilter\Command\Convert;

$application = new Application();
$application->add(new Convert());
$application->run();
